### ISSUE TITLE
how can ı dowland the map ☠

### ISSUE THREAD

**Issue by hamster313131** [Seeloewen/Random-Item-Giver-Datapack#24]
ı dont know how to dowland it pls help

**Comment by Seeloewen** [comment]
You can Download the map through the Planet Minecraft Page (https://www.planetminecraft.com/project/random-item-giver-skyblock/) or directly from this Link: https://mega.nz/file/cgNVWaQY#0IzPdvPXjOOm-oS8lUrVoOBzpnB5JHK-J6F7XjvXEhE

Make sure to use 1.20.6. If you need the map for an older version, let me know.

**Comment by hamster313131** [comment]
thx man it worked!

**Comment by Seeloewen** [comment]
No problem, let me know if you need anything else!
