### ISSUE TITLE
Run a command to give random item to a specific player

### ISSUE THREAD

**Issue by matinmn87** [Seeloewen/Random-Item-Giver-Datapack#5]
Hi again & thanks for your great support on this awesome datapack.
Is there a function to give a specific player random item?

**Comment by Seeloewen** [comment]
You could execute the command **/loot give _{player}_ loot randomitemgiver:1item/main** which gives the player a random item from the main loot table. There are also other loot tables, I can give you a list of them if you want.

**Comment by matinmn87** [comment]
Hello again. Thanks. But what are loot tables?

**Comment by matinmn87** [comment]
Thanks
